# traefik.toml
################################################################
# Global configuration
################################################################
defaultEntryPoints = ["http"]

[entryPoints]

  [entryPoints.http]
     address = ":80"


# defaultEntryPoints = ["http", "https"]

# [entryPoints]
#   [entryPoints.http]
#     address = ":80"
#       [entryPoints.http.redirect]
#       entryPoint = "https"

  # [entryPoints.https]
  #   address = ":443"
  #   compress = true
  #     [entryPoints.https.tls]
  #     MinVersion = "VersionTLS12"


#      regex = "^http://(.*)"
#      replacement = "https://$1"



# To enable forward auth on an entrypoint
    # [entryPoints.http.auth.forward]
    # address = "https://rev-ldap.mlfmonde.org"

# Trust existing X-Forwarded-* headers.
    # Useful with another reverse proxy in front of Traefik.
    #
    # Optional
    # Default: false
    #
    #trustForwardHeader = true
    #
    #

##### Dashboard Auth
  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.auth.basic]
      users = ["anybox:$apr1$MQaILHUt$qf1lK1bHLS9n7RI3.kVfw."]

