---

# tasks file for gitlab-common
- name: Install precondition for Debian Stretch
  raw: apt-get update && apt-get upgrade -y

- name: Install git
  apt:
    name: git-core
    state: present

#Prepare options before installing postfix
#preventing question during installation
- name: Set postfix Internet Site options
  debconf:
    name: postfix
    question: "postfix/main_mailer_type" 
    value: "'Internet Site'" 
    vtype: "string"

- name: Set postfix option hostname
  debconf: 
    name: postfix
    question: "postfix/mailname"
    value: "{{ system_fqdn }}"
    vtype: "string"

- name: Install Postfix
  apt:
   name: postfix
   state: present
   update_cache: yes

- name: Install dependencies
  apt:
    pkg:
        - openssh-server
        - curl
        - ca-certificates
        - nfs-common
        - htop
        - vim
    state: present

# Used by the next module, in order to create the
# extension needed in the DB
- name: Install python3-psycopg2
  apt:
    name: python3-psycopg2
    state: present


- name: Create extension
  postgresql_ext:
    name: "{{ postgres_gitlab_ext }}"
    db: "{{ postgress_default_db }}"
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_pass }}"  

# Create directory needed by gitlab
# to be mount point for NFS
- name: Create NFS mount point
  file:
    path: "{{ gitlab_datadir }}"
    state: directory
    owner: admin
    group: admin

# Create entry in /etc/fstab and mount NFS
# Make sure is mounted before installing gitlab
- name: Create NFS Option
  mount:
    name: "{{ gitlab_datadir }}"
    src: "{{ efs_dnsname }}:/"
    fstype: nfs
    opts: "defaults,vers=4.1"
    state: mounted


- name: Copy install script 
  copy:
    src: script.deb.sh
    dest: /usr/local/bin/script.deb.sh 
    owner: root
    group: root
    mode: 0750
# Script provided by gitlab omnibus to isntall repo and gpg key
- name: Install repository
  command: /usr/local/bin/script.deb.sh
  args:
    creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list

- name: Install gitlab-ce
  apt: 
    name: gitlab-ce
    state: present

# Gitlab omnibus config file
- name: Copy configuration file
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600

# Install Anybox Certificate
- name: Copy Anybox Certificate
  copy:
    src: Anybox_CA2.crt
    dest: /usr/local/share/ca-certificates/Anybox_CA2.crt
    owner: root
    group: root
    mode: 0750

- name: Configure certificate
  command: update-ca-certificates


- name: Configure gitlab-ce
  command: gitlab-ctl reconfigure
  args:
    creates: /etc/systemd/system/basic.target.wants/gitlab-runsvdir.service

 # Creates an entry cron backup"
- cron:
    name: "Backup Gitlab"
    minute: "0"
    hour: "*/1"
    job: "gitlab-rake gitlab:backup:create > /dev/null"
